tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "mas"
mas "Xcode", id: 497799835
mas "Slack", id: 803453959


brew "boost"
brew "cmake"
brew "cryptopp"
brew "gmp"
brew "openssl@1.1"
brew "gdal"
brew "gnuplot", args: ["with-aquaterm"]
brew "go"
brew "graphviz"
brew "leveldb"
brew "llvm"
brew "node"
brew "opencv"
brew "tree"
brew "docker"
brew "git"
brew "glew"
brew "glfw"
brew "pcl"
brew "pdal"
brew "wget"
cask "godot"
cask "google-chrome"
cask "abyssoft-teleport"